version: '3'
services:
  cmqa:
    restart: always
    build:
      context: ./
    env_file:
      - ./env
    links:
      - db
    depends_on:
      - db
    tty: true
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "main.js"]
  db:
    restart: always
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - ./_postgresql:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: cmqa
      POSTGRES_USER: cmqa
      POSTGRES_PASSWORD: cmqa